#!/bin/bash

if [ $# -ne 3 ]; then
    echo $0: usage: backup_BabyLuigi VM VM_Drive_Location BackupLocation
    exit 1
fi

VM=$1
Loc=$2
Backup=$3

today=$(date +%m-%d-%Y)

echo "Shutting down" $VM

#virsh shutdown $VM

while true; do

	if [$(virsh domstate CheepCheep | grep 'running')]; then 
		echo "still running"
	else
		break
	fi
done

echo "Copying the main drive"

#cp $Loc/$VM.qcow2 $Backup/current

echo "Copying the XML"

#virsh dumpxml $VM > $Backup/current/$VM_backup.xml

echo "Tarring it Up"

#tar cvzf $Backup/$VM$today.tar.gz $Backup/current/

echo "Cleaning "$Backup"/current directory"

#rm $Backup/current/*

echo "Starting "$VM" back up"

#virsh start $VM

